export const marketingContent = {
  ar: {
    header: {
      projects: 'المشاريع',
      services: 'الخدمات',
      contact: 'تواصل',
      pricing: 'الأسعار',
      login: 'دخول',
      dashboard: 'لوحتي',
      controllers: 'لوحة الإدارة',
      language: 'اللغة',
    },
    hero: {
      topInfo: 'مجموعة الابتكار الرقمي والتقنية',
      brandTagline: 'نـــــبــــنــــي الــــمــــســــتــــقـــبــــل',
      primaryCta: 'ابدأ البناء',
      secondaryCta: 'تواصل معنا',
      techTitle: 'تقنية NIXT',
      techLine1: 'حلول برمجية متكاملة',
      techLine2: 'وتطوير أنظمة ذكية',
      servicesTitle: 'الخدمات',
      servicesLine1: 'تطوير الويب | التطبيقات | SaaS',
      servicesLine2: 'بنية تحتية سحابية',
      brandingTitle: 'الهوية',
      brandingLine1: 'تصميم إبداعي',
      brandingLine2: 'حلول رقمية',
    },
    logoTicker: {
      title: 'أعمالنا',
    },
    bento: {
      titleLine1: 'نحن نطوّر',
      titleLine2: 'كل شيء.',
      leadDescription: 'من مواقع مذهلة إلى أنظمة محاسبية معقدة تخدم الملايين. إذا كان بإمكانك تخيله، يمكننا بناؤه.',
      logicTitle: 'منطق أعمال ذكي',
      logicDescription: 'أنظمة محاسبية مخصصة وسير عمل ذكي مصمم وفق قواعد شركتك.',
      processing: 'جارٍ معالجة المنطق...',
      scaleTitle: 'أنظمة عالية التوسع',
      scaleDescription: 'بنى قوية مصممة للتعامل مع ملايين المستخدمين النشطين دون توقف.',
      webTitle: 'منصات الويب',
      webDescription: 'مواقع ولوحات تحكم حديثة ومتجاوبة مبنية بأحدث التقنيات.',
      webPrompt: 'ماذا ستنشئ اليوم؟',
      commerceTitle: 'التجارة الإلكترونية',
      commerceDescription: 'متاجر وأسواق رقمية قوية ومهيأة لرفع التحويلات إلى أقصى حد.',
      paymentTitle: 'معالجة المدفوعات',
      paymentDescription: 'ندير تكاملات الدفع والفوترة وعمليات التحويل المعقدة لأعمالك.',
      saasTitle: 'SaaS للمؤسسات',
      saasDescription: 'منصات متعددة المستأجرين تمكّنك من خدمة آلاف العملاء من الشركات.',
      infraLabel: 'بنية تحتية محددة بالإطار',
      infraPrimary: 'من الفكرة إلى الإنتاج بسرعة قياسية.',
      infraSecondary: 'تفهم Nixt Group احتياجاتك بعمق لتوفير الموارد المناسبة وتحسين الأداء للتطبيقات عالية الكفاءة.',
    },
    projects: {
      title: 'مشاريع مختارة',
      items: [
        {
          badge: 'SaaS',
          title: 'مدير سير العمل',
          description: 'منصة تحسن العمليات عبر التحليلات والوصول الآمن.',
          cta: 'لنبدأ به',
        },
        {
          badge: 'سحابة',
          title: 'بنية عالمية',
          description: 'بنية متوسعة تلقائياً تخدم الملايين دون توقف.',
          cta: 'اختره لمشروعك',
        },
        {
          badge: 'UX',
          title: 'إعادة تصميم تجاري',
          description: 'إعادة تصميم متمحورة حول المستخدم رفعت التحويل بنسبة 28%.',
          cta: 'لنبنه معاً',
        },
      ],
    },
    services: {
      title: 'جوهر الابتكار',
      subtitle: 'نصمم تجارب رقمية تمزج بين التقنية المتقدمة والتصميم المتمحور حول الإنسان.',
      items: [
        {
          title: 'تطوير الأنظمة',
          description: 'لا نبني مواقع فقط؛ بل نصمم أنظمة قوية تدير أعمالك بكفاءة عالية وأمان متقدم مع مراعاة كل التفاصيل التقنية.',
        },
        {
          title: 'حلول سحابية',
          description: 'بنية تحتية متقدمة تضمن استقرار مشروعك وقابليته للتوسع عالمياً دون عوائق تقنية أو برمجية.',
        },
        {
          title: 'تجربة المستخدم',
          description: 'تصاميم حديثة تركز على نفسية المستخدم وسهولة الوصول كما في أبرز المنصات التقنية العالمية.',
        },
      ],
      learnMore: 'اعرف المزيد',
    },
    productDirection: {
      label: 'الجدول الزمني لمشروع العميل',
      title: 'تابع كل خطوة، لحظياً.',
      strong: 'شفافية كاملة لراحة بالك.',
      description: 'نوفر لك جدولاً زمنياً مخصصاً لمشروعك يوضح ما تم إنجازه يومياً بدقة. راقب التقدم والتحديثات والمحطات الرئيسية في أي وقت.',
      planningPhase: 'المرحلة 1: التخطيط',
      systemDesign: 'تصميم النظام',
      development: 'التطوير',
      deployment: 'الإطلاق والتشغيل',
    },
    footer: {
      companyTitle: 'الشركة',
      legalTitle: 'القانونية',
      brandDescription: 'نبني تجارب رقمية تصنع المستقبل. ابتكار ودقة وتميّز في كل سطر برمجي.',
      companyLinks: [
        { label: 'نبذة', href: '#hero' },
        { label: 'الخدمات', href: '#services' },
        { label: 'المشاريع', href: '#projects' },
        { label: 'تواصل', href: 'https://wa.me/972599909455' },
      ],
      legalLinks: [
        { label: 'سياسة الخصوصية', href: '/privacy-policy' },
        { label: 'الشروط والأحكام', href: '/terms-of-service' },
        { label: 'سياسة الكوكيز', href: '/cookie-policy' },
      ],
      privacy: 'الخصوصية',
      terms: 'الشروط',
    //   sitemap: 'خريطة الموقع',
      copyrightSuffix: 'Nixt Group. جميع الحقوق محفوظة.',
    },
    pricing: {
      title: 'أسعار واضحة',
      subtitle: 'أسعار ابتدائية واضحة للمشاريع المركزة، مع عروض مخصصة للنطاقات الأكبر والخصائص الأكثر تعقيداً.',
      startingFrom: 'تبدأ من $',
      mostPopular: 'الأكثر طلباً',
      cards: [
        {
          title: 'صفحة هبوط',
          price: '100',
          summary: 'يعتمد السعر النهائي على عدد الصفحات والخصائص وتعقيد المشروع.',
          features: [
            'حتى 5 أقسام مخصصة',
            'دمج نموذج التواصل',
            'تجاوب كامل للجوال وسطح المكتب',
            'تهيئة SEO أساسية',
            'دمج التحليلات',
            'أداء محسن',
            '7 أيام دعم بعد الإطلاق',
            'كود نظيف وقابل للصيانة',
          ],
          cta: 'ابدأ الآن',
        },
        {
          title: 'لوحة تحكم',
          price: '200',
          summary: 'يعتمد السعر النهائي على التكاملات وسير العمل وتعقيد المشروع.',
          features: [
            'نظام مصادقة',
            'صلاحيات وأدوار المستخدمين',
            'لوحة إدارة',
            'رسوم وتقارير',
            'تكامل API',
            'واجهة متجاوبة',
            'توثيق مرفق',
            'دعم إصلاح الأخطاء بعد الإطلاق',
          ],
          cta: 'ابدأ مشروعك',
        },
        {
          title: 'تجارة إلكترونية',
          price: '500',
          summary: 'يعتمد السعر النهائي على حجم المنتجات ومتطلبات الدفع وتعقيد المشروع.',
          features: [
            'إدارة كتالوج المنتجات',
            'سلة شراء وعملية دفع',
            'تكامل بوابات الدفع',
            'إدارة الطلبات',
            'حسابات العملاء',
            'لوحة إدارة',
            'بنية قابلة للتوسع',
            'توثيق مرفق',
          ],
          cta: 'اطلب عرض سعر',
        },
      ],
      customTitle: 'تحتاج شيئاً مخصصاً؟',
      customDescription1: 'إذا كنت تحتاج منصة SaaS أو نظام CRM أو لوحة أعمال أو حلاً للتجارة الإلكترونية أو تطبيق ويب مخصصاً، يمكننا تصميم حل يناسب أهدافك وميزانيتك.',
      customDescription2: 'الخطوات: 1. أخبرنا عن مشروعك. 2. استلم عرضاً مخصصاً. 3. نبدأ بناء الحل.',
      customCta: 'اطلب عرض سعر',
    },
  },
  en: {
    header: {
      projects: 'Projects',
      services: 'Services',
      contact: 'Contact',
      pricing: 'Pricing',
      login: 'Login',
      dashboard: 'Dashboard',
      controllers: 'Controllers',
      language: 'Language',
    },
    hero: {
      topInfo: 'DIGITAL INNOVATION & TECH GROUP',
      brandTagline: 'building the future',
      primaryCta: 'Start Building',
      secondaryCta: 'Get in Touch',
      techTitle: 'NIXT TECH',
      techLine1: 'Integrated Software Solutions',
      techLine2: '& Smart Systems Development',
      servicesTitle: 'SERVICES',
      servicesLine1: 'Web Development | Apps | SaaS',
      servicesLine2: 'Cloud Infrastructure',
      brandingTitle: 'BRANDING',
      brandingLine1: 'CREATIVE DESIGN',
      brandingLine2: 'DIGITAL SOLUTIONS',
    },
    logoTicker: {
      title: 'Our Projects',
    },
    bento: {
      titleLine1: 'We engineer',
      titleLine2: 'Everything.',
      leadDescription: 'From stunning websites to complex accounting systems serving millions. If you can imagine it, we build it.',
      logicTitle: 'Smart Business Logic',
      logicDescription: 'Custom accounting systems and intelligent workflows tailored to your company\'s rules.',
      processing: 'Processing Logic...',
      scaleTitle: 'High-Scale Systems',
      scaleDescription: 'Robust architectures designed to handle millions of active users without downtime.',
      webTitle: 'Web Platforms',
      webDescription: 'Modern, responsive websites & dashboards built with cutting-edge tech.',
      webPrompt: 'What will you create?',
      commerceTitle: 'E-Commerce',
      commerceDescription: 'Powerful online stores and marketplaces optimized for maximum conversion.',
      paymentTitle: 'Payment Processing',
      paymentDescription: 'We handle complex payment gateways, invoicing, and payout operations for your business.',
      saasTitle: 'Enterprise SaaS',
      saasDescription: 'Multi-tenant platforms enabling you to serve thousands of corporate clients.',
      infraLabel: 'Framework-Defined Infrastructure',
      infraPrimary: 'From concept to production in record time.',
      infraSecondary: 'Nixt Group deeply understands your needs to provision the right resources and optimize for high-performance apps.',
    },
    projects: {
      title: 'Featured Projects',
      items: [
        {
          badge: 'SaaS',
          title: 'Workflow Manager',
          description: 'Platform optimizing operations with analytics and secure access.',
          cta: 'Start with this',
        },
        {
          badge: 'Cloud',
          title: 'Global Infra',
          description: 'Auto-scaled infrastructure serving millions with zero downtime.',
          cta: 'Choose this',
        },
        {
          badge: 'UX',
          title: 'Commerce Redesign',
          description: 'Human-centered redesign improved conversion by 28%.',
          cta: 'Let\'s build it',
        },
      ],
    },
    services: {
      title: 'The Essence of Innovation',
      subtitle: 'Crafting digital experiences that merge cutting-edge technology with human-centric design.',
      items: [
        {
          title: 'Systems Development',
          description: 'We don\'t just build websites; we design powerful systems that manage your business with high efficiency and superior security, considering every technical detail.',
        },
        {
          title: 'Cloud Solutions',
          description: 'Advanced infrastructure ensuring complete stability for your project and the ability to scale globally without any technical or software obstacles.',
        },
        {
          title: 'User Experience',
          description: 'Modern designs focused on user psychology and accessibility, just as seen in the world\'s most prestigious tech platforms.',
        },
      ],
      learnMore: 'Learn more',
    },
    productDirection: {
      label: 'Client Project Timeline',
      title: 'Track Every Step, Real-Time.',
      strong: 'Complete transparency for your peace of mind.',
      description: 'We provide a dedicated timeline for your project that details exactly what happened every day. Monitor progress, updates, and milestones at any time.',
      planningPhase: 'Phase 1: Planning',
      systemDesign: 'System Design',
      development: 'Development',
      deployment: 'Deployment & Live',
    },
    footer: {
      companyTitle: 'Company',
      legalTitle: 'Legal',
      brandDescription: 'We build digital experiences that define the future. Innovation, precision, and excellence in every line of code.',
      companyLinks: [
        { label: 'About', href: '#hero' },
        { label: 'Services', href: '#services' },
        { label: 'Projects', href: '#projects' },
        { label: 'Contact', href: 'https://wa.me/972599909455' },
      ],
      legalLinks: [
        { label: 'Privacy Policy', href: '/privacy-policy' },
        { label: 'Terms of Service', href: '/terms-of-service' },
        { label: 'Cookie Policy', href: '/cookie-policy' },
      ],
      privacy: 'Privacy',
      terms: 'Terms',
    //   sitemap: 'Sitemap',
      copyrightSuffix: 'Nixt Group. All rights reserved.',
    },
    pricing: {
      title: 'Transparent Pricing',
      subtitle: 'Clear starting prices for focused builds, with custom quotes for larger scopes and more complex features.',
      startingFrom: 'Starting from $',
      mostPopular: 'Most Popular',
      cards: [
        {
          title: 'Landing Page',
          price: '100',
          summary: 'Final pricing depends on the page count, features, and project complexity.',
          features: [
            'Up to 5 Custom Sections',
            'Contact Form Integration',
            'Mobile & Desktop Responsive',
            'Basic SEO Setup',
            'Analytics Integration',
            'Performance Optimized',
            '7 Days of Post-Launch Support',
            'Clean, Maintainable Code',
          ],
          cta: 'Get Started',
        },
        {
          title: 'Dashboard',
          price: '200',
          summary: 'Final pricing depends on the integrations, workflows, and project complexity.',
          features: [
            'Authentication System',
            'User Roles & Permissions',
            'Admin Dashboard',
            'Charts & Reports',
            'API Integration',
            'Responsive Interface',
            'Documentation Included',
            'Bug Fix Support After Launch',
          ],
          cta: 'Start Your Project',
        },
        {
          title: 'E-Commerce',
          price: '500',
          summary: 'Final pricing depends on product scope, payment requirements, and project complexity.',
          features: [
            'Product Catalog Management',
            'Shopping Cart & Checkout',
            'Payment Gateway Integration',
            'Order Management',
            'Customer Accounts',
            'Admin Panel',
            'Scalable Architecture',
            'Documentation Included',
          ],
          cta: 'Request a Quote',
        },
      ],
      customTitle: 'Need something custom?',
      customDescription1: 'If you need a SaaS platform, CRM system, business dashboard, e-commerce solution, or custom web application, we can scope a solution around your goals and budget.',
      customDescription2: 'Process: 1. Tell us about your project. 2. Receive a custom proposal. 3. We start building your solution.',
      customCta: 'Request a Quote',
    },
  },
} as const

export type MarketingLanguage = keyof typeof marketingContent